if: >-
  repo   = 'CodeForPoznan/Infrastructure'

env:
  - TF_INPUT=false

install:
- |
  cd /tmp
  wget --quiet https://releases.hashicorp.com/terraform/0.12.21/terraform_0.12.21_linux_amd64.zip
  unzip $(basename $_)
  export PATH="$PATH:/tmp"

script:
- terraform validate
- terraform fmt -check -recursive -diff
