name: lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CodeForPoznan/actions/setup-infrastructure@v2
        with:
          terraform-version: 1.5.3

      - run: make check

  data:
    uses: CodeForPoznan/actions/.github/workflows/call-validate-data-files.yml@v2
