name: lint


on:
  push:
    branches: [main]
    paths: ['**/**.tf']
  pull_request:
    branches: [main]
    paths: ['**/**.tf']


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
          terraform_wrapper: false

      - run: make check
