name: lint tf

on:
  push:
    branches: [main]
    paths: ['**/**.tf']
  pull_request:
    branches: [main]
    paths: ['**/**.tf']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: CodeForPoznan/actions/setup-infrastructure@v2
        with:
          terraform-version: 1.3.0

      - run: make check
