name: lint


on:
  pull_request:
    branches: [master]
    paths: ['**.tf']


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.0
          terraform_wrapper: false

      - run: terraform fmt -check -recursive -diff
