name: lint


on:
  push:
    branches: [main]
    paths: ['**/**.tf']
  pull_request:
    branches: [main]
    paths: ['**/**.tf']


jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CodeForPoznan/actions/setup-terraform@v2
        with:
          terraform-version: 1.1.8

      - run: make check
      - run: make validate

